#include "encode.h"
#include "meteor_ctx.h"
#include "prng.h"
#include "bits.h"
#include "meteor_core.h"
#include "llm_client.h"

#include <stdlib.h>
#include <string.h>
#include <stdio.h>

/* Maximum syllable string length for joining a partial word. */
#define MAX_PARTIAL_LEN 512

char* meteor_encode_impl(struct MeteorCtx* ctx,
                         const uint8_t*    message,
                         size_t            msg_len,
                         const char*       starting_context,
                         MeteorProgressFn  progress_cb,
                         void*             progress_userdata,
                         int*              out_error)
{
    *out_error = METEOR_OK;

    /* convert message to bit array */
    size_t   total_bits;
    uint8_t* msg_bits = bits_from_bytes(message, msg_len, &total_bits);
    if (!msg_bits) { *out_error = METEOR_ERR_OOM; return NULL; }

    /* seed PRNG */
    MeteorPRNG prng;
    int rc = prng_init_raw(&prng, ctx->key);
    if (rc != 0) {
        free(msg_bits);
        *out_error = METEOR_ERR_CRYPTO;
        return NULL;
    }

    /* build style preamble (NULL in legacy mode) */
    char* preamble = llm_client_build_preamble((int)ctx->style, starting_context);

    /* allocate output buffer; in style mode the covertext starts empty */
    size_t ctx_len = (ctx->style == METEOR_STYLE_NONE && starting_context)
                     ? strlen(starting_context) : 0;
    size_t buf_cap  = ctx_len + (size_t)ctx->max_steps * 32 + 64;
    char*  full_text = (char*)malloc(buf_cap);
    if (!full_text) {
        free(preamble);
        free(msg_bits);
        prng_wipe(&prng);
        *out_error = METEOR_ERR_OOM;
        return NULL;
    }
    if (ctx_len > 0)
        memcpy(full_text, starting_context, ctx_len);
    full_text[ctx_len] = '\0';

    /* Style mode: the opening phrase is generated by the LLM loop itself
       (first call sees an empty "sentence so far"), so no fixed literal
       opener is injected here — see build_phrase_prompt's ctx_len==0 case. */

    size_t bit_offset = 0;
    int    steps      = 0;

    if (ctx->style != METEOR_STYLE_NONE) {
        /* Hard reject: even at theoretical maximum (beta bits/step × max_steps)
           the step budget cannot hold the message. */
        if ((size_t)(ctx->max_steps * ctx->beta) < total_bits) {
            free(preamble); free(msg_bits); free(full_text); prng_wipe(&prng);
            *out_error = METEOR_ERR_CAPACITY;
            return NULL;
        }

        /* ── Phrase-level encode loop (style mode) ──────────────────────── */
        /* Blacklist the last few phrases (not just the immediately previous
           one) so a slot-driven pick two steps back can't be re-picked and
           produce visible repetition ("commutes early ... commutes early"). */
        #define PHRASE_HISTORY 6
        char phrase_history[PHRASE_HISTORY][64] = {{0}};
        int  hist_count = 0;
        char subject_anchor[64] = {0};
        MeteorWordHistory content_hist = {0};
        StyleQuestionHistory q_hist = {0};
        ClauseState clause_state = {0};
        DigressionState digress_state = {0};
        DigressionAxisHistory axis_hist = {0};
        int sentence_is_digression = 0;
        DigressionAxis sentence_axis = DIGRESS_AXIS_DESCRIBE;
        int sentence_variant = 0;
        while (bit_offset < total_bits && steps < ctx->max_steps) {
            /* Drawn every iteration (even the opening step, which doesn't
               use it) so the PRNG stream advances identically regardless
               of ctx_len — see meteor_draw_style_question() in
               meteor_core.h for the lockstep requirement with decode.c. */
            StyleQuestion question = meteor_draw_style_question(&prng, &q_hist);
            meteor_style_question_history_push(&q_hist, question);

            /* Also drawn every iteration for the same lockstep reason —
               see meteor_draw_clause_end() in meteor_core.h. */
            int end_clause = meteor_draw_clause_end(&prng, &clause_state);

            /* Also drawn every iteration for the same lockstep reason —
               see meteor_draw_digress_mode()/meteor_draw_digression_axis()/
               meteor_draw_digression_variant() in meteor_core.h. Only
               consulted below when this iteration turns out to be a
               sentence-opening step (subject_anchor empty); discarded
               otherwise, same as `question` on opening steps. */
            int            digress = meteor_draw_digress_mode(&prng, &digress_state);
            DigressionAxis axis    = meteor_draw_digression_axis(&prng, &axis_hist);
            meteor_digression_axis_history_push(&axis_hist, axis);
            int            variant = meteor_draw_digression_variant(&prng);

            /* Latch this sentence's mode/axis/variant at its opening step
               so the clause-end branch (many iterations later) can still
               update digress_state with the decision that was actually
               used — the locals above are redrawn fresh every iteration
               and no longer reflect it by then. */
            int is_opening = (subject_anchor[0] == '\0');
            if (is_opening) {
                sentence_is_digression = digress;
                sentence_axis          = axis;
                sentence_variant       = variant;
            }

            char blacklist_buf[512] = {0};
            size_t bl_off = 0;
            for (int i = 0; i < hist_count; i++) {
                int w = snprintf(blacklist_buf + bl_off, sizeof(blacklist_buf) - bl_off,
                                  "%s%s", i > 0 ? ", " : "", phrase_history[i]);
                if (w > 0) bl_off += (size_t)w;
            }
            char word_blacklist_buf[256] = {0};
            meteor_word_history_join(&content_hist, word_blacklist_buf,
                                      sizeof(word_blacklist_buf));

            /* Digression opening step: stage 1 asks a non-bit-embedding
               question about a secondary entity and gets back an answer;
               stage 2 paraphrases that answer via a one-off temporary
               preamble instead of the main topic preamble, through the
               exact same call as a normal topic-anchored opening. See
               llm_client_get_digression_answer() in llm_client.h. */
            char* digress_answer   = NULL;
            char* digress_preamble = NULL;
            if (is_opening && sentence_is_digression) {
                digress_answer = llm_client_get_digression_answer(
                    ctx->llm, full_text, sentence_axis, sentence_variant);
                if (!digress_answer) { *out_error = METEOR_ERR_OOM; break; }
                digress_preamble = llm_client_build_preamble((int)ctx->style, digress_answer);
                if (!digress_preamble) { free(digress_answer); *out_error = METEOR_ERR_OOM; break; }
            }

            LLMResponse* resp = llm_client_get_phrase_dist(
                ctx->llm, digress_preamble ? digress_preamble : preamble, full_text,
                hist_count > 0 ? blacklist_buf : NULL,
                word_blacklist_buf[0] ? word_blacklist_buf : NULL,
                subject_anchor[0] ? subject_anchor : NULL,
                question);
            free(digress_answer);
            free(digress_preamble);
            if (!resp) { *out_error = METEOR_ERR_LLM; break; }

            const char** p_texts = (const char**)malloc((size_t)resp->count * sizeof(char*));
            float*       p_probs = (float*)malloc((size_t)resp->count * sizeof(float));
            if (!p_texts || !p_probs) {
                free(p_texts); free(p_probs); llm_response_free(resp);
                *out_error = METEOR_ERR_OOM; break;
            }
            for (int i = 0; i < resp->count; i++) {
                p_texts[i] = resp->candidates[i].text;
                p_probs[i] = resp->candidates[i].prob;
            }
            MeteorDist* dist = meteor_build_dist(p_texts, p_probs, resp->count, ctx->beta);
            free(p_texts); free(p_probs); llm_response_free(resp);
            if (!dist) { *out_error = METEOR_ERR_OOM; break; }

            MeteorStepResult step = meteor_encode_step(
                dist, msg_bits, bit_offset, total_bits, &prng, ctx->beta);
            meteor_free_dist(dist);

            bit_offset += (size_t)step.cp_len;
            steps++;
            if (progress_cb)
                progress_cb(progress_userdata, steps, (int)bit_offset, (int)total_bits);

            if (subject_anchor[0] == '\0') {
                strncpy(subject_anchor, step.chosen, 63);
                subject_anchor[63] = '\0';
            }

            meteor_word_history_add(&content_hist, step.chosen);

            if (hist_count < PHRASE_HISTORY) {
                strncpy(phrase_history[hist_count], step.chosen, 63);
                phrase_history[hist_count][63] = '\0';
                hist_count++;
            } else {
                for (int i = 0; i < PHRASE_HISTORY - 1; i++)
                    memcpy(phrase_history[i], phrase_history[i + 1], 64);
                strncpy(phrase_history[PHRASE_HISTORY - 1], step.chosen, 63);
                phrase_history[PHRASE_HISTORY - 1][63] = '\0';
            }

            /* append chosen phrase (may contain spaces) to covertext */
            size_t plen   = strlen(step.chosen);
            size_t ft_len = strlen(full_text);
            size_t needed = ft_len + 1 + plen + 2;
            if (needed > buf_cap) {
                buf_cap = needed * 2;
                char* tmp = (char*)realloc(full_text, buf_cap);
                if (!tmp) { *out_error = METEOR_ERR_OOM; free(full_text); full_text = NULL; break; }
                full_text = tmp;
            }
            if (ft_len > 0) full_text[ft_len++] = ' ';
            memcpy(full_text + ft_len, step.chosen, plen);
            full_text[ft_len + plen] = '\0';

            clause_state.phrases_in_sentence++;
            if (end_clause) {
                size_t c_ft_len = strlen(full_text);
                size_t c_needed = c_ft_len + 2;
                if (c_needed > buf_cap) {
                    buf_cap = c_needed * 2;
                    char* tmp = (char*)realloc(full_text, buf_cap);
                    if (!tmp) { *out_error = METEOR_ERR_OOM; free(full_text); full_text = NULL; break; }
                    full_text = tmp;
                }
                full_text[c_ft_len]     = '.';
                full_text[c_ft_len + 1] = '\0';
                subject_anchor[0] = '\0';
                clause_state.phrases_in_sentence = 0;

                digress_state.last_was_digression = sentence_is_digression;
                if (!sentence_is_digression) digress_state.topic_sentences_completed++;
            }
        }
        /* Force a closing period if the loop ended mid-sentence (the last
           clause-end draw said "continue"). Deterministic — no PRNG bits
           needed — so decode does not need to mirror this: decode stops
           consuming the covertext the moment it recovers the null
           terminator and never looks at whatever trailing text follows. */
        if (*out_error == METEOR_OK && full_text) {
            size_t f_len = strlen(full_text);
            if (f_len > 0 && full_text[f_len - 1] != '.') {
                size_t needed = f_len + 2;
                if (needed > buf_cap) {
                    buf_cap = needed * 2;
                    char* tmp = (char*)realloc(full_text, buf_cap);
                    if (tmp) full_text = tmp;
                    else { *out_error = METEOR_ERR_OOM; free(full_text); full_text = NULL; }
                }
                if (full_text) {
                    full_text[f_len]     = '.';
                    full_text[f_len + 1] = '\0';
                }
            }
        }
        #undef PHRASE_HISTORY
    } else {
        /* ── Syllable-level encode loop (legacy mode) ───────────────────── */
        char partial_word[MAX_PARTIAL_LEN] = {0};

        while ((bit_offset < total_bits || partial_word[0] != '\0') && steps < ctx->max_steps) {
            int is_new_word = (partial_word[0] == '\0');

            LLMResponse* resp = llm_client_get_syllable_dist(
                ctx->llm, preamble, full_text, partial_word, is_new_word);
            if (!resp) { *out_error = METEOR_ERR_LLM; break; }

            const char** syl_texts = (const char**)malloc((size_t)resp->count * sizeof(char*));
            float*       syl_probs = (float*)malloc((size_t)resp->count * sizeof(float));
            if (!syl_texts || !syl_probs) {
                free(syl_texts); free(syl_probs); llm_response_free(resp);
                *out_error = METEOR_ERR_OOM; break;
            }
            for (int i = 0; i < resp->count; i++) {
                syl_texts[i] = resp->candidates[i].text;
                syl_probs[i] = resp->candidates[i].prob;
            }
            MeteorDist* dist = meteor_build_dist(syl_texts, syl_probs, resp->count, ctx->beta);
            free(syl_texts); free(syl_probs); llm_response_free(resp);
            if (!dist) { *out_error = METEOR_ERR_OOM; break; }

            MeteorStepResult step = meteor_encode_step(
                dist, msg_bits, bit_offset, total_bits, &prng, ctx->beta);
            meteor_free_dist(dist);

            bit_offset += (size_t)step.cp_len;
            steps++;
            if (progress_cb)
                progress_cb(progress_userdata, steps, (int)bit_offset, (int)total_bits);

            if (strcmp(step.chosen, EOW_TOKEN) == 0) {
                size_t pw_len = strlen(partial_word);
                size_t ft_len = strlen(full_text);
                size_t needed = ft_len + 1 + pw_len + 2;
                if (needed > buf_cap) {
                    buf_cap = needed * 2;
                    char* tmp = (char*)realloc(full_text, buf_cap);
                    if (!tmp) { *out_error = METEOR_ERR_OOM; free(full_text); full_text = NULL; break; }
                    full_text = tmp;
                }
                if (ft_len > 0) full_text[ft_len++] = ' ';
                memcpy(full_text + ft_len, partial_word, pw_len);
                full_text[ft_len + pw_len] = '\0';
                partial_word[0] = '\0';
            } else {
                strncat(partial_word, step.chosen, MAX_PARTIAL_LEN - strlen(partial_word) - 1);
            }
        }

        /* finalise any dangling partial word */
        if (partial_word[0] != '\0' && full_text) {
            size_t pw_len = strlen(partial_word);
            size_t ft_len = strlen(full_text);
            size_t needed = ft_len + 1 + pw_len + 2;
            if (needed > buf_cap) {
                char* tmp = (char*)realloc(full_text, needed);
                if (!tmp) { *out_error = METEOR_ERR_OOM; free(full_text); full_text = NULL; }
                else full_text = tmp;
            }
            if (full_text) {
                if (ft_len > 0) full_text[ft_len++] = ' ';
                memcpy(full_text + ft_len, partial_word, pw_len);
                full_text[ft_len + pw_len] = '\0';
            }
        }
    }

    free(preamble);
    free(msg_bits);
    prng_wipe(&prng);

    if (!full_text) return NULL;
    if (*out_error != METEOR_OK && *out_error != METEOR_ERR_LLM) {
        free(full_text);
        return NULL;
    }
    return full_text;
}
